FreezeLine/Models/FreezeLineContext.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace FreezeLine.Models
{
    public class FreezeLineContext : DbContext
    {
        // You can add custom code to this file. Changes will not be overwritten.
        // 
        // If you want Entity Framework to drop and regenerate your database
        // automatically whenever you change your model schema, please use data migrations.
        // For more information refer to the documentation:
        // http://msdn.microsoft.com/en-us/data/jj591621.aspx
    
        public FreezeLineContext() : base("name=SqlServer")
        {
        }

        public System.Data.Entity.DbSet<FreezeLine.Models.Produto> Produtoes { get; set; }
    }
}

FreezeLine/Models/Produto.cs
using System.ComponentModel.DataAnnotations;

namespace FreezeLine.Models
{
    public class Produto
    {
        public int Id { get; set; }

        [StringLength(10)]
        [Display(Name = "Código")]
        public string Apelido { get; set; }

        [StringLength(100)]
        [Display(Name = "Descrição")]
        public string Descricao { get; set; }

        [Display(Name = "Peso Líquido")]
        [DisplayFormat(DataFormatString = "{0:N4}")]
        public float PesoLiquido { get; set; }

        [Display(Name = "Ativo")]
        public bool Ativo { get; set; }

        [Display(Name = "IPI")]
        [DisplayFormat(DataFormatString = "{0:P0}")]
        public float Ipi { get; set; }

        [Display(Name = "Qt/un")]
        public float QtdUnid { get; set; }

        [StringLength(16)]
        [Display(Name = "Ref Auxiliar Produto")]
        public string RefAuxiliarProduto { get; set; }

        [Display(Name = "Qt Un por Un Armz")]
        public int QtUnPorUnArmz { get; set; }

        [Display(Name = "Peso Líquido Calculado")]
        [DisplayFormat(DataFormatString = "{0:N4}")]
        public float PesoLiquidoCalc { get; set; }

        [Display(Name = "Item Estrutura")]
        public int ItemStru { get; set; }

        [Display(Name = "Custo Direto Total")]
        [DisplayFormat(DataFormatString = "{0:N2}")]
        public float CustODirTotal { get; set; }

        [Display(Name = "Custo Mat última etapa")]
        [DisplayFormat(DataFormatString = "{0:N2}")]
        public float CstMatUltmEtapa { get; set; }

        [Display(Name = "Custo Mat etapa 1")]
        [DisplayFormat(DataFormatString = "{0:N2}")]
        public float CstMatEtapa1 { get; set; }

        [Display(Name = "Custo Mat etapa 2")]
        [DisplayFormat(DataFormatString = "{0:N2}")]
        public float CstMatEtapa2 { get; set; }

        [Display(Name = "Custo Mat etapa 3")]
        [DisplayFormat(DataFormatString = "{0:N2}")]
        public float CstMatEtapa3 { get; set; }

        [Display(Name = "Custo Tot Materiais")]
        [DisplayFormat(DataFormatString = "{0:N2}")]
        public float CstTotMaterial { get; set; }

        [Display(Name = "Custo Direto MOD")]
        [DisplayFormat(DataFormatString = "{0:N2}")]
        public float CustoDirMod { get; set; }

        [Display(Name = "Horas MOD última etapa")]
        [DisplayFormat(DataFormatString = "{0:N3}")]
        public float HorasModUltmEtapa { get; set; }

        [Display(Name = "Horas MOD etapa 1")]
        [DisplayFormat(DataFormatString = "{0:N3}")]
        public float HorasModEtapa1 { get; set; }

        [Display(Name = "Horas MOD etapa 2")]
        [DisplayFormat(DataFormatString = "{0:N3}")]
        public float HorasModEtapa2 { get; set; }
    }
}

FreezeLine/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FreezeLine.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

FreezeLine/Controllers/ProdutoesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FreezeLine.Models;

namespace FreezeLine.Controllers
{
    public class ProdutoesController : Controller
    {
        private FreezeLineContext db = new FreezeLineContext();

        // GET: Produtoes
        public ActionResult Index()
        {
            return View(db.Produtoes.ToList());
        }

        // GET: Produtoes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Produto produto = db.Produtoes.Find(id);
            if (produto == null)
            {
                return HttpNotFound();
            }
            return View(produto);
        }

        // GET: Produtoes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Produtoes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Apelido,Descricao,PesoLiquido,Ativo,Ipi,QtdUnid,RefAuxiliarProduto,QtUnPorUnArmz,PesoLiquidoCalc,ItemStru,CustODirTotal,CstMatUltmEtapa,CstMatEtapa1,CstMatEtapa2,CstMatEtapa3,CstTotMaterial,CustoDirMod,HorasModUltmEtapa,HorasModEtapa1,HorasModEtapa2")] Produto produto)
        {
            if (ModelState.IsValid)
            {
                db.Produtoes.Add(produto);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(produto);
        }

        // GET: Produtoes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Produto produto = db.Produtoes.Find(id);
            if (produto == null)
            {
                return HttpNotFound();
            }
            return View(produto);
        }

        // POST: Produtoes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Apelido,Descricao,PesoLiquido,Ativo,Ipi,QtdUnid,RefAuxiliarProduto,QtUnPorUnArmz,PesoLiquidoCalc,ItemStru,CustODirTotal,CstMatUltmEtapa,CstMatEtapa1,CstMatEtapa2,CstMatEtapa3,CstTotMaterial,CustoDirMod,HorasModUltmEtapa,HorasModEtapa1,HorasModEtapa2")] Produto produto)
        {
            if (ModelState.IsValid)
            {
                db.Entry(produto).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(produto);
        }

        // GET: Produtoes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Produto produto = db.Produtoes.Find(id);
            if (produto == null)
            {
                return HttpNotFound();
            }
            return View(produto);
        }

        // POST: Produtoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Produto produto = db.Produtoes.Find(id);
            db.Produtoes.Remove(produto);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FreezeLine/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

FreezeLine/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

FreezeLine/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div>
    <h1>@Html.ActionLink("<---- Aqui --->", "Index", "Produtoes")</h1>
</div>

FreezeLine/Views/Produtoes/Create.cshtml
@model FreezeLine.Models.Produto

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Produto</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Apelido, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Apelido, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Apelido, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PesoLiquido, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PesoLiquido, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PesoLiquido, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ativo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Ativo)
                    @Html.ValidationMessageFor(model => model.Ativo, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ipi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ipi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ipi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.QtdUnid, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.QtdUnid, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.QtdUnid, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RefAuxiliarProduto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RefAuxiliarProduto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RefAuxiliarProduto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.QtUnPorUnArmz, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.QtUnPorUnArmz, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.QtUnPorUnArmz, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PesoLiquidoCalc, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PesoLiquidoCalc, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PesoLiquidoCalc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ItemStru, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ItemStru, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ItemStru, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CustODirTotal, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CustODirTotal, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CustODirTotal, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CstMatUltmEtapa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CstMatUltmEtapa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CstMatUltmEtapa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CstMatEtapa1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CstMatEtapa1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CstMatEtapa1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CstMatEtapa2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CstMatEtapa2, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CstMatEtapa2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CstMatEtapa3, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CstMatEtapa3, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CstMatEtapa3, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CstTotMaterial, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CstTotMaterial, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CstTotMaterial, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CustoDirMod, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CustoDirMod, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CustoDirMod, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HorasModUltmEtapa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HorasModUltmEtapa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HorasModUltmEtapa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HorasModEtapa1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HorasModEtapa1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HorasModEtapa1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HorasModEtapa2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HorasModEtapa2, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HorasModEtapa2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FreezeLine/Views/Produtoes/Delete.cshtml
@model FreezeLine.Models.Produto

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Produto</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Apelido)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Apelido)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descricao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PesoLiquido)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PesoLiquido)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ativo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ativo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ipi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ipi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.QtdUnid)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.QtdUnid)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RefAuxiliarProduto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RefAuxiliarProduto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.QtUnPorUnArmz)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.QtUnPorUnArmz)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PesoLiquidoCalc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PesoLiquidoCalc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ItemStru)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ItemStru)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CustODirTotal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CustODirTotal)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CstMatUltmEtapa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CstMatUltmEtapa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CstMatEtapa1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CstMatEtapa1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CstMatEtapa2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CstMatEtapa2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CstMatEtapa3)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CstMatEtapa3)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CstTotMaterial)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CstTotMaterial)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CustoDirMod)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CustoDirMod)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HorasModUltmEtapa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HorasModUltmEtapa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HorasModEtapa1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HorasModEtapa1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HorasModEtapa2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HorasModEtapa2)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

FreezeLine/Views/Produtoes/Details.cshtml
@model FreezeLine.Models.Produto

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Produto</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Apelido)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Apelido)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descricao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PesoLiquido)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PesoLiquido)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ativo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ativo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ipi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ipi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.QtdUnid)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.QtdUnid)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RefAuxiliarProduto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RefAuxiliarProduto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.QtUnPorUnArmz)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.QtUnPorUnArmz)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PesoLiquidoCalc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PesoLiquidoCalc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ItemStru)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ItemStru)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CustODirTotal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CustODirTotal)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CstMatUltmEtapa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CstMatUltmEtapa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CstMatEtapa1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CstMatEtapa1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CstMatEtapa2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CstMatEtapa2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CstMatEtapa3)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CstMatEtapa3)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CstTotMaterial)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CstTotMaterial)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CustoDirMod)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CustoDirMod)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HorasModUltmEtapa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HorasModUltmEtapa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HorasModEtapa1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HorasModEtapa1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HorasModEtapa2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HorasModEtapa2)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

FreezeLine/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=10; IE=9; IE=8; IE=7; IE=EDGE" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>